server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/atcrowdfunding?serverTimezone=GMT%2b8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: SCW-USER
  redis:
    host: 192.168.188.129
    port: 6379
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  file:
    path: D:\javaX\logging
  level:
    com:
      offcn: debug
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appCode: APPCODE 1c59a131c267402d8e4337664e139d98

#mybatis:
# mapper-locations: classpath:com/offcn/user/mapper
# config.location: classpath:mybatis/mybatis-config.xml